<script setup>
import { CheckCircleOutlined, FileTextOutlined, FormOutlined, PlusOutlined, RightOutlined, TeamOutlined, TrophyOutlined, UserOutlined } from '@ant-design/icons-vue'
import { useShellContext } from '../../shellContext'
const { session, role, classId, loading, dashboard, latestOverviewAssignment, assignmentHistory, assignmentChartLine, assignmentChartPoints, currentTeam, needsTopicSubmission, studentPendingAssignments, studentUpcomingAssignments, studentPendingReviews, studentLatestGrade, formatTime, openClassCreate, navigate } = useShellContext()
</script>

<template>
  <div class="page-title"><div><div class="eyebrow">{{ role==='TEACHER'?'教师工作台':'学生学习台' }}</div><h1>{{ session.context?.current_class?.name || '还没有教学班' }}</h1><p>{{ classId ? (role==='TEACHER'?'掌握教学班、小组和课程任务的整体进展。':'查看我的小组、待完成作业和课程反馈。') : (role==='TEACHER'?'创建教学班后即可导入学生并开展课程。':'请联系教师加入教学班。') }}</p></div><a-button v-if="role==='TEACHER'&&!classId" type="primary" @click="openClassCreate"><PlusOutlined /> 创建教学班</a-button></div>
  <a-empty v-if="!classId" description="暂无教学班"/>
  <div v-else-if="role==='TEACHER'" class="stat-grid"><div class="stat-card"><UserOutlined class="stat-icon blue"/><div class="stat-body"><span>教学班人数</span><strong>{{ dashboard?.summary.member_count||0 }}<small>人</small></strong></div></div><div class="stat-card"><TeamOutlined class="stat-icon purple"/><div class="stat-body"><span>当前小组</span><strong>{{ dashboard?.summary.team_count||0 }}<small>组</small></strong></div></div><div class="stat-card"><UserOutlined class="stat-icon orange"/><div class="stat-body"><span>未进入小组</span><strong>{{ dashboard?.summary.ungrouped_member_count||0 }}<small>人</small></strong></div></div><div class="stat-card assignment-stat-card"><FileTextOutlined class="stat-icon green"/><div class="stat-body"><span>进行中作业</span><strong>{{ dashboard?.summary.active_assignments||0 }}<small>项</small></strong></div><button class="overview-submission-shortcut" :disabled="loading||!latestOverviewAssignment" :title="latestOverviewAssignment?`查看 ${latestOverviewAssignment.title} 的提交情况`:`暂无作业`" @click="navigate(`/assignments/${latestOverviewAssignment.id}?tab=submission`)"><span>最近作业提交情况</span><RightOutlined/></button></div></div>
  <section v-if="role==='TEACHER'&&classId" class="completion-chart-panel"><div class="completion-chart-heading"><div><h2>最近作业完成情况</h2><span>按截止时间展示最近 6 次作业的提交完成率</span></div><strong v-if="assignmentHistory.length">{{assignmentHistory.at(-1).completion_rate}}%</strong></div><a-empty v-if="!assignmentHistory.length" description="暂无作业完成数据"/><div v-else class="completion-chart-scroll"><div class="completion-chart"><div class="chart-y-axis"><span>100%</span><span>50%</span><span>0%</span></div><svg viewBox="0 0 920 200" preserveAspectRatio="none" role="img" aria-label="最近作业完成率折线图"><line v-for="y in [18,100,182]" :key="y" x1="0" :y1="y" x2="920" :y2="y" class="chart-grid-line"/><polyline :points="assignmentChartLine" class="chart-line"/><g v-for="point in assignmentChartPoints" :key="point.id"><circle :cx="point.x" :cy="point.y" r="6" class="chart-point"/><text :x="point.x" :y="Math.max(13,point.y-12)" text-anchor="middle" class="chart-value">{{point.completion_rate}}%</text></g></svg><div class="chart-labels"><span v-for="(point,index) in assignmentChartPoints" :key="point.id" :class="{first:index===0,last:index===assignmentChartPoints.length-1}" :title="point.title" :style="{left:`${point.x/9.2}%`}">{{point.title}}</span></div></div></div></section>
  <div v-else class="student-overview"><a-card class="student-focus" :bordered="false"><TeamOutlined class="student-focus-icon purple"/><div><span>当前小组与选题</span><strong>{{currentTeam?.name||'尚未加入小组'}}</strong><p>{{currentTeam?.topic?.name||'暂未提交选题'}}</p></div></a-card><div class="stat-grid"><div class="stat-card"><FileTextOutlined class="stat-icon blue"/><div class="stat-body"><span>待提交作业</span><strong>{{studentPendingAssignments.length}}<small>项</small></strong></div></div><div class="stat-card"><CheckCircleOutlined class="stat-icon orange"/><div class="stat-body"><span>72 小时内截止</span><strong>{{studentUpcomingAssignments.length}}<small>项</small></strong></div></div><div class="stat-card"><FormOutlined class="stat-icon purple"/><div class="stat-body"><span>待完成互评</span><strong>{{studentPendingReviews}}<small>份</small></strong></div></div><div class="stat-card"><TrophyOutlined class="stat-icon green"/><div class="stat-body"><span>最新成绩</span><strong>{{studentLatestGrade?(studentLatestGrade.final_grade||studentLatestGrade.score):'-' }}</strong></div></div></div><a-card class="panel-card student-todo-card" :bordered="false"><div class="card-toolbar"><strong>近期待办</strong></div><a-empty v-if="!needsTopicSubmission&&!studentPendingAssignments.length&&!studentPendingReviews" description="当前没有待完成事项"/><div v-if="needsTopicSubmission" class="student-todo-row actionable" @click="navigate(`/teams?team=${currentTeam.id}`)"><TeamOutlined/><div><strong>提交小组选题</strong><span>小组已创建，请完善选题并提交审核</span></div><a-tag color="orange">待提交</a-tag></div><div v-for="item in studentPendingAssignments.slice(0,3)" :key="item.id" class="student-todo-row actionable" @click="navigate(`/assignments/${item.id}`)"><FileTextOutlined/><div><strong>{{item.title}}</strong><span>截止 {{formatTime(item.due_at)}}</span></div><a-tag v-if="item.starts_at&&new Date(item.starts_at)>new Date()">未开始</a-tag><a-tag v-else color="orange">待提交</a-tag></div><div v-if="studentPendingReviews" class="student-todo-row actionable" @click="navigate('/reviews')"><FormOutlined/><div><strong>组内作品互评</strong><span>还有 {{studentPendingReviews}} 份评价待完成</span></div><a-tag color="blue">待互评</a-tag></div></a-card></div>
</template>
