<script setup>
import { CheckCircleOutlined, CloseOutlined, EyeOutlined, PlusOutlined } from '@ant-design/icons-vue'
import { useShellContext } from '../../shellContext'
const { session, role, teams, requests, ungroupedMembers, modals, formatTime, statusLabel, applyTeam, openTeam, decideTopic, decideRequest, respondInvitation, cancelRequest } = useShellContext()
</script>

<template>
  <div class="page-title"><div><div class="eyebrow">{{ role==='TEACHER'?'教学组织':session.teamGate?'开始课程前':'协作空间' }}</div><h1>{{ role==='TEACHER'?'小组与选题':session.teamGate?'加入小组':'我的小组' }}</h1><p>{{ role==='TEACHER'?'审核各组选题，查看成员配置并处理异常。':session.teamGate?'创建小组或申请加入已有小组。入组后将自动进入教学班首页。':'管理本组成员、邀请和选题信息。' }}</p></div><a-button v-if="role==='STUDENT'&&session.teamGate" type="primary" @click="modals.team=true"><PlusOutlined /> 创建小组</a-button></div>
  <a-alert v-if="session.teamGate" type="info" show-icon message="加入小组后解锁课程功能" class="soft-alert"/>
  <div v-if="role==='STUDENT'" class="team-grid"><a-card v-for="item in teams" :key="item.id" class="team-card" :bordered="false"><div class="team-card-top"><a-avatar shape="square">{{item.name.slice(0,1)}}</a-avatar><a-tag :color="item.open_recruitment?'blue':'default'">{{item.open_recruitment?'招募中':'未开放'}}</a-tag></div><h3>{{item.name}}</h3><p>{{item.topic?.name||(session.context?.current_class?.topic_public?'暂未提交选题':'选题未公开')}}</p><div class="team-card-meta"><span>{{item.member_count}} 人</span><span>组长：{{item.leader_name}}</span></div><a-divider/><a-space wrap><a-button v-if="session.teamGate&&item.open_recruitment" type="primary" ghost @click="applyTeam(item)">申请加入</a-button><a-button v-if="item.is_leader" type="primary" @click="openTeam(item)">{{item.topic?'修改选题':'提交选题'}}</a-button><a-button @click="openTeam(item)">查看详情</a-button></a-space></a-card><a-empty v-if="!teams.length" description="暂无小组，可创建第一个小组"/></div>
  <a-card v-else class="panel-card" :bordered="false"><a-table :data-source="teams" row-key="id"><a-table-column title="小组" data-index="name"/><a-table-column title="组长" data-index="leader_name"/><a-table-column title="人数" data-index="member_count"/><a-table-column title="选题"><template #default="{record}">{{record.topic?.name||'-'}}</template></a-table-column><a-table-column title="操作"><template #default="{record}"><a-space><a-tooltip title="查看小组"><a-button type="text" shape="circle" @click="openTeam(record)"><EyeOutlined/></a-button></a-tooltip><a-tooltip v-if="record.topic?.status==='PENDING'" title="通过选题"><a-button type="text" shape="circle" @click="decideTopic(record,'APPROVED')"><CheckCircleOutlined/></a-button></a-tooltip><a-tooltip v-if="record.topic?.status==='PENDING'" title="退回选题"><a-button danger type="text" shape="circle" @click="decideTopic(record,'REJECTED')"><CloseOutlined/></a-button></a-tooltip></a-space></template></a-table-column></a-table></a-card>
  <a-card v-if="role==='TEACHER'" class="panel-card ungrouped-members-panel" :bordered="false"><div class="card-toolbar"><div><strong>未进入小组学生</strong><span class="class-member-caption">{{ungroupedMembers.length}} 人</span></div></div><a-empty v-if="!ungroupedMembers.length" description="所有学生均已进入小组"/><a-table v-else :data-source="ungroupedMembers" row-key="id" size="small" :pagination="{pageSize:10}"><a-table-column title="学号" data-index="student_no"/><a-table-column title="姓名" data-index="name"/><a-table-column title="加入教学班时间"><template #default="{record}">{{formatTime(record.joined_at)}}</template></a-table-column></a-table></a-card>
  <a-card v-if="role==='STUDENT'&&requests.length" class="panel-card request-card" title="入组申请与邀请" :bordered="false"><div v-for="item in requests" :key="item.id" class="request-row"><div><strong>{{item.is_incoming?item.applicant_name:item.team_name}}</strong><span>{{item.kind==='INVITATION'?'小组邀请':item.is_incoming?'申请加入你的小组':`申请状态：${statusLabel(item.status)}`}}</span></div><a-space v-if="item.is_incoming&&item.kind==='APPLICATION'&&item.status==='PENDING'"><a-button @click="decideRequest(item,'REJECTED')">拒绝</a-button><a-button type="primary" @click="decideRequest(item,'APPROVED')">同意</a-button></a-space><a-space v-else-if="item.kind==='INVITATION'&&!item.is_incoming&&item.status==='PENDING'"><a-button @click="respondInvitation(item,'REJECTED')">拒绝</a-button><a-button type="primary" @click="respondInvitation(item,'APPROVED')">接受</a-button></a-space><a-button v-else-if="!item.is_incoming&&item.status==='PENDING'" @click="cancelRequest(item)">取消申请</a-button><a-tag v-else>{{statusLabel(item.status)}}</a-tag></div></a-card>
</template>
